# Importing Libraries

In [1012]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

# Reading CSV Datasets

In [1013]:
order_df = pd.read_csv(r"C:\Users\Admin\OneDrive\Desktop\project\p2\data\olist_orders_dataset.csv")
items_df = pd.read_csv(r'C:\Users\Admin\OneDrive\Desktop\project\p2\data\olist_order_items_dataset.csv')
products_df = pd.read_csv(r'C:\Users\Admin\OneDrive\Desktop\project\p2\data\olist_products_dataset.csv')
customers_df = pd.read_csv(r'C:\Users\Admin\OneDrive\Desktop\project\p2\data\olist_customers_dataset.csv')

# Data Exloration

### First and last values

In [1014]:
order_df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [1015]:
order_df.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [1016]:
items_df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [1017]:
items_df.tail()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [1018]:
products_df.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [1019]:
products_df.tail()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0

In [1020]:
customers_df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [1021]:
customers_df.tail()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

### shape

In [1022]:
def get_shape(df):
    return df.shape

get_shape(order_df)

(99441, 8)

In [1023]:
get_shape(items_df)

(112650, 7)

In [1024]:
get_shape(products_df)

(32951, 9)

In [1025]:
get_shape(customers_df)

(99441, 5)

### Columns

In [1026]:
def get_column(df):
    return df.columns

get_column(order_df)

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [1027]:
get_column(items_df)

Index(['order_id', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value'],
      dtype='str')

In [1028]:
get_column(products_df)

Index(['product_id', 'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm'],
      dtype='str')

In [1029]:
get_column(customers_df)

Index(['customer_id', 'customer_unique_id', 'customer_zip_code_prefix',
       'customer_city', 'customer_state'],
      dtype='str')

### Data Types

In [1030]:
def get_data_type(df):
    return df.dtypes

get_data_type(order_df)

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [1031]:
get_data_type(items_df)

order_id                   str
order_item_id            int64
product_id                 str
seller_id                  str
shipping_limit_date        str
price                  float64
freight_value          float64
dtype: object

In [1032]:
get_data_type(products_df)

product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

In [1033]:
get_data_type(customers_df)

customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object

### Missing values

In [1034]:
def get_missing_values(df):
    return df.isna().sum()

get_missing_values(order_df)

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [1035]:
get_missing_values(items_df)

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [1036]:
get_missing_values(products_df)

product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

In [1037]:
get_missing_values(customers_df)

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

# Data Cleaning

## cleaning order dataset

In [1038]:
order_df.head(1)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00

In [1039]:
def converting_dates(df):
    '''
    converting the date columns
    '''

    date_columns = [
        'order_purchase_timestamp',
        'order_approved_at',
        'order_delivered_carrier_date',
        'order_delivered_customer_date',
        'order_estimated_delivery_date',
        'shipping_limit_date'
    ]

    for col in date_columns:
        if col in df.columns:
            df[col] = pd.to_datetime(df[col], errors='coerce')

    return df


order_df = converting_dates(order_df)
products_df = converting_dates(products_df)
items_df = converting_dates(items_df)
customers_df = converting_dates(customers_df)

In [1040]:
oid  = order_df['order_id'].is_unique
oid

True

In [1041]:
cid = order_df['customer_id'].is_unique

In [1042]:
order_df['order_status'].value_counts()

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: int64

In [1043]:
invalid_carrier = order_df[order_df['order_delivered_carrier_date'] < order_df['order_purchase_timestamp']]

In [1044]:
difference = (invalid_carrier['order_purchase_timestamp'] - invalid_carrier['order_delivered_carrier_date'])

difference.describe()

count                        166
mean      1 days 02:02:22.120481
std      13 days 06:55:25.842359
min              0 days 00:00:24
25%              0 days 00:14:04
50%       0 days 00:35:59.500000
75%              0 days 01:01:03
max            171 days 05:05:53
dtype: object

In [1045]:
invalid_carrier['order_status'].value_counts()

order_status
delivered    165
shipped        1
Name: count, dtype: int64

In [1046]:
difference[difference > pd.Timedelta(days=1)]

25883   171 days 05:05:53
83321     4 days 05:27:40
dtype: timedelta64[us]

## cleaning product dataset

In [1047]:
products_df.head(15)

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0
5,41d3672d4792049fa1779bb35283ed13,instrumentos_musicais,60.0,745.0,1.0,200.0,38.0,5.0,11.0
6,732bd381ad09e530fe0a5f457d81becb,cool_stuff,56.0,1272.0,4.0,18350.0,70.0,24.0,44.0
7,2548af3e6e77a690cf3eb6368e9ab61e,moveis_decoracao,56.0,184.0,2.0,900.0,40.0,8.0,40.0
8,37cc742be07708b53a98702e77a21a02,eletrodomesticos,57.0,163.0,1.0,400.0,27.0,13.0,17.0
9,8c92109888e8cdf9d66dc7e463025574,brinquedos,36.0,1156.0,1.0,600.0,17.0,10.0,12.0
10,14aa47b7fe5c25522b47b4b29c98dcb9,cama_mesa_banho,54.0,630.0,1.0,1100.0,16.0,10.0,16.0
11,03b63c5fc16691530586ae020c345514,bebes,49.0,728.0,4.0,7150.0,50.0,19.0,45.0
12,cf55509ea8edaaac1d28fdb16e48fc22,instrumentos_musicais,43.0,1827.0,3.0,250.0,17.0,7.0,17.0
13,7bb6f29c2be57716194f96496660c7c2,moveis_decoracao,51.0,2083.0,2.0,600.0,68.0,11.0,13.0
14,eb31436580a610f202c859463d8c7415,construcao_ferramentas_seguranca,59.0,1602.0,4.0,200.0,17.0,7.0,17.0

In [1048]:
missing_category = products_df[products_df['product_category_name'].isna()]

In [1049]:
products_df['product_id'].is_unique

True

In [1050]:
products_df.duplicated().sum()

np.int64(0)

In [1051]:
missing_category = products_df[products_df['product_category_name'].isna()]
items_df[items_df['product_id'].isin(missing_category['product_id'])]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
123,0046e1d57f4c07c8c92ab26be8c3dfc0,1,ff6caf9340512b8bf6d2a2a6df032cfa,38e6dada03429a47197d5d584d793b41,2017-10-02 15:49:17,7.79,7.78
125,00482f2670787292280e0a8153d82467,1,a9c404971d1a5b1cbc2e4070e02731fd,702835e4b785b67a084280efca355756,2017-02-17 16:18:07,7.60,10.96
132,004f5d8f238e8908e6864b874eda3391,1,5a848e4ab52fd5445cdc07aab1c40e48,c826c40d7b19f62a09e2d7c5e7295ee2,2018-03-06 09:29:25,122.99,15.61
142,0057199db02d1a5ef41bacbf41f8f63b,1,41eee23c25f7a574dfaf8d5c151dbb12,e5a3438891c0bfdb9394643f95273d8e,2018-01-25 09:07:51,20.30,16.79
171,006cb7cafc99b29548d4f412c7f9f493,1,e10758160da97891c2fdcbc35f0f031d,323ce52b5b81df2cd804b017b7f09aa7,2018-02-22 13:35:28,56.00,14.14
...,...,...,...,...,...,...,...
112306,ff24fec69b7f3d30f9dc1ab3aee7c179,1,5a848e4ab52fd5445cdc07aab1c40e48,c826c40d7b19f62a09e2d7c5e7295ee2,2018-02-01 02:40:12,122.99,15.61
112333,ff3024474be86400847879103757d1fd,1,f9b1795281ce51b1cf39ef6d101ae8ab,3771c85bac139d2344864ede5d9341e3,2017-11-21 03:55:39,39.90,9.94
112350,ff3a45ee744a7c1f8096d2e72c1a23e4,1,b61d1388a17e3f547d2bc218df02335b,07017df32dc5f2f1d2801e579548d620,2017-05-10 10:15:19,139.00,21.42
112438,ff7b636282b98e0aa524264b295ed928,1,431df35e52c10451171d8037482eeb43,6cd68b3ed6d59aaa9fece558ad360c0a,2018-02-22 15:35:35,49.90,15.11
112501,ffa5e4c604dea4f0a59d19cc2322ac19,2,bd421826916d3e1d445cb860cea3c0fb,59cd88080b93f3c18508673122d26169,2017-12-11 08:41:20,29.99,15.10

## Customer dataset

In [1052]:
customers_df.head(1)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP

In [1053]:
customers_df['customer_id'].is_unique

True

In [1054]:
customers_df['customer_unique_id'].value_counts().head(1)

customer_unique_id
8d50f5eadf50201ccdcedfb9e2ac8455    17
Name: count, dtype: int64

In [1055]:
customers_df[customers_df['customer_unique_id'] == '8d50f5eadf50201ccdcedfb9e2ac8455']

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
14186,1bd3585471932167ab72a84955ebefea,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
15321,a8fabc805e9a10a3c93ae5bff642b86b,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
16654,897b7f72042714efaa64ac306ba0cafc,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
36122,b2b13de0770e06de50080fea77c459e6,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
38073,42dbc1ad9d560637c9c4c1533746f86d,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
40141,dfb941d6f7b02f57a44c3b7c3fefb44b,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
48614,65f9db9dd07a4e79b625effa4c868fcb,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
52574,1c62b48fb34ee043310dcb233caabd2e,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
58707,a682769c4bc10fc6ef2101337a6c83c9,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
67996,6289b75219d757a56c0cce8d9e427900,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
72745,3414a9c813e3ca02504b8be8b2deb27f,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
74510,0e4fdc084a6b9329ed55d62dcd653ccf,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
83363,f5188d99e9281e214a4a7d1b139a8229,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
85507,89be66634d68fa73a95499b6352e085d,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
90268,0bf8bf19944a7f8b40ba86fef778ca7c,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
93591,9a1afef458843a022e431f4cb304dfe9,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP
96652,31dd055624c66f291578297a551a6cdf,8d50f5eadf50201ccdcedfb9e2ac8455,4045,sao paulo,SP

## Order items Dataset

In [1056]:
items_df.head(1)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29

In [1057]:
items_df.duplicated().sum()

np.int64(0)

In [1058]:
items_df.isna().sum()

order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

In [1059]:
items_df['order_id'].nunique()

98666

In [1060]:
items_df[items_df['order_item_id'] == 5]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
562,0148d3df00cebda592d4e5f966e300cc,5,ed08ea04c92f5f434c2362f7310fb328,0adac9fbd9a2b63cccaac4f8756c1ca8,2017-08-24 19:24:32,5.53,11.85
1136,02a065131a2d2b72b45e2c63135606ad,5,993245facdeea0014e73a3e18750c123,1025f0e2d44d7041d6cf58b6550e0bfa,2018-05-03 03:35:19,125.00,26.95
1241,02e0c2efb6d9bb2a95ca90b7e78bec1f,5,f4041d76285c2a34ad5013e8d287a400,1835b56ce799e6a4dc4eddc053f04066,2018-04-05 11:07:40,39.99,12.79
1502,03705afa0a4aabe1a734ddb11c1df3f0,5,b40ec43bdfc6d6fdd65e882066a5c895,897060da8b9a21f655304d50fd935913,2017-10-03 08:49:34,177.00,27.78
1597,03aba68b07658f28f29612641f08d4ba,5,e7cc48a9daff5436f63d3aad9426f28b,53243585a1d6dc2643021fd1853d8905,2018-08-15 08:50:17,170.00,30.44
...,...,...,...,...,...,...,...
110570,fb3cf8c9eb2412b0edc0a00a8f43a869,5,4cceacaeb21aa22aa51b4c724de3758d,157c3e4b42f81ac4a44e8b1ca2fe9876,2018-06-06 14:31:55,90.00,8.22
110677,fb7d6ea70e823cfb1afca3524282cbf9,5,53759a2ecddad2bb87a079a1f1519f73,1f50f920176fa81dab994f9023523100,2018-04-09 05:28:15,53.90,21.35
110720,fb8e4428d340ab5bfa482ef6fc97efbc,5,53b36df67ebb7c41585e8d54d6772e08,4869f7a5dfa277a7dca6462dcf3b52b2,2017-09-08 08:44:16,169.90,12.69
110895,fbf6a5df377654baa14f40156140e563,5,98a4301b1aacd45984603af55b7a1de4,1900267e848ceeba8fa32d80c1a5f5a8,2018-03-20 02:55:26,53.00,13.73
111254,fcbe557f2bb4cd2409d67dec35a1e6f3,5,0a9c1531aa7c17c8c64157b634fa9ba9,86ccac0b835037332a596a33b6949ee1,2017-08-25 14:30:24,29.99,15.10

In [1061]:
items_df['product_id'].value_counts()

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
                                   ...
4cc4d02efc8f249c13355147fb44e34d      1
b10ecf8e33aaaea419a9fa860ea80fb5      1
dd469c03ad67e201bc2179ef077dcd48      1
bbe7651fef80287a816ead73f065fc4b      1
350688d9dc1e75ff97be326363655e01      1
Name: count, Length: 32951, dtype: int64

In [1062]:
items_df[items_df['product_id'] == '368c6c730842d78016ad823897a372db']

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
13,0008288aa423d2a3f00fcb17cd7d8719,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.9,13.37
14,0008288aa423d2a3f00fcb17cd7d8719,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-21 02:55:52,49.9,13.37
319,00c842d0ae6462afc1d38fc055b02c75,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2017-11-14 17:55:27,59.9,17.67
647,017cf0b342401318dcaeb25478e13a6f,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-01-10 23:17:29,49.9,17.60
731,01b241fa1421c8284e8c1029a503360f,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2017-12-06 00:25:28,59.0,17.66
...,...,...,...,...,...,...,...
110157,fa4e26319fe4d40dc11cb63c53be6355,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-02-15 23:07:56,49.9,13.37
110173,fa54be41eb7ceaa9e9909bb015372f49,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-01-03 12:48:36,49.9,17.60
110501,fb160817be895543f88cd2eb3d7b1946,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2017-12-13 21:50:43,59.0,17.66
110502,fb160817be895543f88cd2eb3d7b1946,2,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2017-12-13 21:50:43,59.0,17.66
111454,fd2aee7994becefcf7b6dc6b6b9e7621,1,368c6c730842d78016ad823897a372db,1f50f920176fa81dab994f9023523100,2018-03-09 14:10:24,53.9,17.63

In [1063]:
items_df.dtypes

order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

## making a temporary report

In [1064]:
def cleanin_report(df):
    print('=' * 40)
    print('            Cleaning Reoprt ')
    print('=' * 40)

    # ================================
    #            Shape
    # ================================
    
    print('\nShape:')
    print(f'Shape before the Cleaaning: {df.shape}')

    # ================================
    #          Duplicated
    # ================================

    print('\nDuplicated values:')
    print(f'Duplicated values: {df.duplicated().sum()}')

    # ================================
    #         Missing values
    # ================================

    print(f'\nMissing Values: \n{df.isna().sum()}')


    # ================================
    #         Data types
    # ================================

    print(f'\nData types: \n{df.dtypes}')


    # ================================
    #         Data types
    # ================================

    id_col = [
        'order_id',
        'customers_id'
    ]

    for col in id_col:
        if col in df.columns:
            if (cid, oid) == (True, True):
                print('\nAll Order ids are unique')
                print('\nAll customer_id values in the orders dataset are unique.')
            else:
                print('IDs are not unique!!')

    print('=' * 60)

In [1065]:
cleanin_report(order_df)

========================================
            Cleaning Reoprt
========================================

Shape:
Shape before the Cleaaning: (99441, 8)

Duplicated values:
Duplicated values: 0

Missing Values:
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

Data types:
order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

All Order ids are unique

All customer_id values in the orders dataset are unique.
============================================================

In [1066]:
cleanin_report(products_df)

========================================
            Cleaning Reoprt
========================================

Shape:
Shape before the Cleaaning: (32951, 9)

Duplicated values:
Duplicated values: 0

Missing Values:
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Data types:
product_id                        str
product_category_name             str
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object
============================================================

In [1067]:
cleanin_report(items_df)

========================================
            Cleaning Reoprt
========================================

Shape:
Shape before the Cleaaning: (112650, 7)

Duplicated values:
Duplicated values: 0

Missing Values:
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64

Data types:
order_id                          str
order_item_id                   int64
product_id                        str
seller_id                         str
shipping_limit_date    datetime64[us]
price                         float64
freight_value                 float64
dtype: object

All Order ids are unique

All customer_id values in the orders dataset are unique.
============================================================

In [1068]:
cleanin_report(customers_df)

========================================
            Cleaning Reoprt
========================================

Shape:
Shape before the Cleaaning: (99441, 5)

Duplicated values:
Duplicated values: 0

Missing Values:
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64

Data types:
customer_id                   str
customer_unique_id            str
customer_zip_code_prefix    int64
customer_city                 str
customer_state                str
dtype: object
============================================================

# Merging Datasets

In [1069]:
customer_orders = customers_df.merge(order_df, on='customer_id')

In [1070]:
customer_orders.shape

(99441, 12)

In [1071]:
customer_orders.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,2017-05-25 10:35:35,2017-06-05
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,2018-01-29 12:41:19,2018-02-06
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,2018-06-14 17:58:51,2018-06-13
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,2018-03-28 16:04:25,2018-04-10
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,2018-08-09 20:55:48,2018-08-15

In [1072]:
customer_orders.tail()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,6760e20addcf0121e9d58f2f1ff14298,delivered,2018-04-07 15:48:17,2018-04-07 16:08:45,2018-04-11 02:08:36,2018-04-13 20:06:37,2018-04-25
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,9ec0c8947d973db4f4e8dcf1fbfa8f1b,delivered,2018-04-04 08:20:22,2018-04-04 08:35:12,2018-04-05 18:42:35,2018-04-11 18:54:45,2018-04-20
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,fed4434add09a6f332ea398efd656a5c,delivered,2018-04-08 20:11:50,2018-04-08 20:30:03,2018-04-09 17:52:17,2018-05-09 19:03:15,2018-05-02
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,e31ec91cea1ecf97797787471f98a8c2,delivered,2017-11-03 21:08:33,2017-11-03 21:31:20,2017-11-06 18:24:41,2017-11-16 19:58:39,2017-12-05
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,28db69209a75e59f20ccbb5c36a20b90,delivered,2017-12-19 14:27:23,2017-12-19 18:50:39,2017-12-21 19:17:21,2017-12-26 18:42:36,2018-01-08

In [1073]:
customer_orders.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 12 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   customer_id                    99441 non-null  str
 1   customer_unique_id             99441 non-null  str
 2   customer_zip_code_prefix       99441 non-null  int64
 3   customer_city                  99441 non-null  str
 4   customer_state                 99441 non-null  str
 5   order_id                       99441 non-null  str
 6   order_status                   99441 non-null  str
 7   order_purchase_timestamp       99441 non-null  datetime64[us]
 8   order_approved_at              99281 non-null  datetime64[us]
 9   order_delivered_carrier_date   97658 non-null  datetime64[us]
 10  order_delivered_customer_date  96476 non-null  datetime64[us]
 11  order_estimated_delivery_date  99441 non-null  datetime64[us]
dtypes: datetime64[us](5), int64(1), str(6)
memory usage: 9.1 MB

In [1074]:
ordered_items = customer_orders.merge(items_df, on='order_id')

In [1075]:
ordered_items.shape

(112650, 18)

In [1076]:
master_df = ordered_items.merge(products_df, on='product_id')

In [1077]:
master_df.shape

(112650, 26)

# Business Analysis

### Business Overview

In [1078]:
master_df.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,124.99,21.88,moveis_escritorio,41.0,1141.0,1.0,8683.0,54.0,64.0,31.0
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-01-12 20:58:32,2018-01-15 17:14:59,...,289.00,46.48,utilidades_domesticas,43.0,1002.0,3.0,10150.0,89.0,15.0,40.0
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-05-20 16:19:10,2018-06-11 14:31:00,...,139.94,17.79,moveis_escritorio,55.0,955.0,1.0,8267.0,52.0,52.0,17.0
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-03-13 17:29:19,2018-03-27 23:22:42,...,149.94,23.36,moveis_escritorio,48.0,1066.0,1.0,12160.0,56.0,51.0,28.0
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-07-29 10:10:09,2018-07-30 15:16:00,...,230.00,22.25,casa_conforto,61.0,407.0,1.0,5200.0,45.0,15.0,35.0

In [1079]:
def total_orders(df):
    return df['order_id'].nunique()

(total_orders(master_df))

98666

In [1080]:
def total_customer(df):
    return df['customer_unique_id'].nunique()

total_customer(master_df)

95420

In [1081]:
def total_products(df):
    return df['product_id'].count()

total_products(master_df)

np.int64(112650)

In [1082]:
def unique_products(df):
    return df['product_id'].nunique()

unique_products(master_df)

32951

In [1083]:
def total_category(df):
    return df['product_category_name'].nunique()

total_category(master_df)

73

In [1084]:
def top_states(df):
    return df.groupby('customer_state')['order_id'].nunique().sort_values(ascending=False).head()

top_states(master_df)

customer_state
SP    41375
RJ    12762
MG    11544
RS     5432
PR     4998
Name: order_id, dtype: int64

In [1085]:
def top_citites(df):
    return df.groupby('customer_city')['order_id'].nunique().sort_values(ascending=False).head(10)

top_citites(master_df)

customer_city
sao paulo                15402
rio de janeiro            6834
belo horizonte            2750
brasilia                  2116
curitiba                  1510
campinas                  1429
porto alegre              1372
salvador                  1238
guarulhos                 1178
sao bernardo do campo      928
Name: order_id, dtype: int64

In [1086]:
def business_overview(df):
    print('=' * 50)
    print('                Business Overview ')
    print('=' * 50)

    print(f'\nTotal orders: {total_orders(df)}')
    print(f'Total Customers: {total_customer(df)}')
    print(f'Total Products: {total_products(df)}')
    print(f'Total Unique Products: {unique_products(df)}')
    print(f'Total Product Categories: {total_category(df)}')
    print(f'\nTop 10 Cities by Orders: \n{top_citites(df)}')
    print(f'\nTop 5 States by Orders: \n{top_states(df)}')

    print('=' * 50)

In [1087]:
business_overview(master_df)

==================================================
                Business Overview
==================================================

Total orders: 98666
Total Customers: 95420
Total Products: 112650
Total Unique Products: 32951
Total Product Categories: 73

Top 10 Cities by Orders:
customer_city
sao paulo                15402
rio de janeiro            6834
belo horizonte            2750
brasilia                  2116
curitiba                  1510
campinas                  1429
porto alegre              1372
salvador                  1238
guarulhos                 1178
sao bernardo do campo      928
Name: order_id, dtype: int64

Top 5 States by Orders:
customer_state
SP    41375
RJ    12762
MG    11544
RS     5432
PR     4998
Name: order_id, dtype: int64
==================================================

# Revenue Analysis

### Revenue metrics

In [1088]:
def total_price_revenue(df):
    return df['price'].sum()

total_price_revenue(master_df)

np.float64(13591643.700000001)

In [1089]:
def total_frieght(df):
    return df['freight_value'].sum()

total_frieght(master_df)

np.float64(2251909.54)

In [1090]:
def total_revenue(df):
    return total_price_revenue(df) + total_frieght(df)

total_revenue(master_df)

np.float64(15843553.240000002)

In [1091]:
def average_order_value(df):
    return total_revenue(df) / total_orders(df)

average_order_value(master_df)

np.float64(160.5776380921493)

In [1092]:
def average_price(df):
    return df['price'].mean()

average_price(master_df)

np.float64(120.65373901464714)

In [1093]:
def average_frieght(df):
    return df['freight_value'].mean()

average_frieght(master_df)

np.float64(19.990319928983578)

### Revenue by Geography

In [1094]:
def revenue_by_state(df):
    return df.groupby('customer_state')['price'].sum().sort_values(ascending=False).head(10)

revenue_by_state(master_df)

customer_state
SP    5202955.05
RJ    1824092.67
MG    1585308.03
RS     750304.02
PR     683083.76
SC     520553.34
BA     511349.99
DF     302603.94
GO     294591.95
ES     275037.31
Name: price, dtype: float64

In [1095]:
def revenue_by_city(df):
    return df.groupby('customer_city')['price'].sum().sort_values(ascending=False).head(10)

revenue_by_city(master_df)

customer_city
sao paulo         1914924.54
rio de janeiro     992538.86
belo horizonte     355611.13
brasilia           301920.25
curitiba           211738.06
porto alegre       190562.08
campinas           187844.53
salvador           181104.42
guarulhos          144268.39
niteroi            117907.12
Name: price, dtype: float64

### Revenue by Category

In [1096]:
def revenue_by_category(df):
    return df.groupby('product_category_name')['price'].sum().sort_values(ascending=False).head(10)

revenue_by_category(master_df)

product_category_name
beleza_saude              1258681.34
relogios_presentes        1205005.68
cama_mesa_banho           1036988.68
esporte_lazer              988048.97
informatica_acessorios     911954.32
moveis_decoracao           729762.49
cool_stuff                 635290.85
utilidades_domesticas      632248.66
automotivo                 592720.11
ferramentas_jardim         485256.46
Name: price, dtype: float64

In [1097]:
def revenue_analysis(df):
    print('=' * 50)
    print('                Revenue Analysis ')
    print('=' * 50)

    print(f'\nTotal Price Revenue: {total_price_revenue(master_df)}')
    print(f'Total Freight: {total_frieght(master_df)}')
    print(f'Total Revenue: {total_revenue(master_df)}')
    print(f'Average Order Value: {average_order_value(master_df)}')
    print(f'Average Price: {average_price(master_df)}')
    print(f'\nAverage Freight: \n{average_frieght(master_df)}')

    print('\nRevenue by Geography')
    print(f'\nTop 10 Sates Revenue: \n{revenue_by_state(master_df)}')
    print(f'\nTop 10 Cities Revenue: \n{revenue_by_city(master_df)}')

    print('\nRevenue by Category')
    print(f'\nTop 10 Category Revenue: \n{revenue_by_category(master_df)}')

    print('=' * 50)

revenue_analysis(master_df)

==================================================
                Revenue Analysis
==================================================

Total Price Revenue: 13591643.700000001
Total Freight: 2251909.54
Total Revenue: 15843553.240000002
Average Order Value: 160.5776380921493
Average Price: 120.65373901464714

Average Freight:
19.990319928983578

Revenue by Geography

Top 10 Sates Revenue:
customer_state
SP    5202955.05
RJ    1824092.67
MG    1585308.03
RS     750304.02
PR     683083.76
SC     520553.34
BA     511349.99
DF     302603.94
GO     294591.95
ES     275037.31
Name: price, dtype: float64

Top 10 Cities Revenue:
customer_city
sao paulo         1914924.54
rio de janeiro     992538.86
belo horizonte     355611.13
brasilia           301920.25
curitiba           211738.06
porto alegre       190562.08
campinas           187844.53
salvador           181104.42
guarulhos          144268.39
niteroi            117907.12
Name: price, dtype: float64

Revenue by Category

Top 10 Category Revenue:
product_category_name
beleza_saude              1258681.34
relogios_presentes        1205005.68
cama_mesa_banho           1036988.68
esporte_lazer              988048.97
informatica_acessorios     911954.32
moveis_decoracao           729762.49
cool_stuff                 635290.85
utilidades_domesticas      632248.66
automotivo                 592720.11
ferramentas_jardim         485256.46
Name: price, dtype: float64
==================================================

# Product Analysis

### Product performance

In [1098]:
def best_selling_product(df):
    return df['product_id'].value_counts().head(10)

best_selling_product(master_df)

product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
53759a2ecddad2bb87a079a1f1519f73    373
d1c427060a0f73f6b889a5c7c61f2ac4    343
53b36df67ebb7c41585e8d54d6772e08    323
154e7e31ebfa092203795c972e5804a6    281
3dd2a17168ec895c781a9191c1e95ad7    274
Name: count, dtype: int64

In [1099]:
def highest_revenue_product(df):
    return df.groupby('product_id')['price'].sum().sort_values(ascending=False).head(10)

highest_revenue_product(master_df)

product_id
bb50f2e236e5eea0100680137654686c    63885.00
6cdd53843498f92890544667809f1595    54730.20
d6160fb7873f184099d9bc95e30376af    48899.34
d1c427060a0f73f6b889a5c7c61f2ac4    47214.51
99a4788cb24856965c36a24e339b6058    43025.56
3dd2a17168ec895c781a9191c1e95ad7    41082.60
25c38557cf793876c5abdd5931f922db    38907.32
5f504b3a1c75b73d6151be81eb05bdc9    37733.90
53b36df67ebb7c41585e8d54d6772e08    37683.42
aca2eb7d00ea1a7b8ebd4e68314663af    37608.90
Name: price, dtype: float64

In [1100]:
def best_selling_categories(df):
    return df.groupby('product_category_name')['order_id'].count().sort_values(ascending=False).head(10)

best_selling_categories(master_df)

product_category_name
cama_mesa_banho           11115
beleza_saude               9670
esporte_lazer              8641
moveis_decoracao           8334
informatica_acessorios     7827
utilidades_domesticas      6964
relogios_presentes         5991
telefonia                  4545
ferramentas_jardim         4347
automotivo                 4235
Name: order_id, dtype: int64

In [1101]:
def highest_revenue_category(df):
    return df.groupby('product_category_name')['price'].sum().sort_values(ascending=False).head(10)

highest_revenue_category(master_df)

product_category_name
beleza_saude              1258681.34
relogios_presentes        1205005.68
cama_mesa_banho           1036988.68
esporte_lazer              988048.97
informatica_acessorios     911954.32
moveis_decoracao           729762.49
cool_stuff                 635290.85
utilidades_domesticas      632248.66
automotivo                 592720.11
ferramentas_jardim         485256.46
Name: price, dtype: float64

In [1102]:
def average_product_price_by_category(df):
    return df.groupby('product_category_name')['price'].mean().sort_values(ascending=False).head(10)

average_product_price_by_category(master_df)

product_category_name
pcs                                              1098.340542
portateis_casa_forno_e_cafe                       624.285658
eletrodomesticos_2                                476.124958
agro_industria_e_comercio                         342.124858
instrumentos_musicais                             281.616000
eletroportateis                                   280.778468
portateis_cozinha_e_preparadores_de_alimentos     264.568667
telefonia_fixa                                    225.693182
construcao_ferramentas_seguranca                  208.992371
relogios_presentes                                201.135984
Name: price, dtype: float64

### Product Characteristics

In [1103]:
def average_weight_by_category(df):
    return df.groupby('product_category_name')['product_weight_g'].mean().head(10)

average_weight_by_category(master_df)

product_category_name
agro_industria_e_comercio    3625.113208
alimentos                     658.115686
alimentos_bebidas            1104.654676
artes                        1557.545455
artes_e_artesanato           1369.875000
artigos_de_festas            1997.674419
artigos_de_natal             1893.712418
audio                        1218.423077
automotivo                   2594.148288
bebes                        3273.405026
Name: product_weight_g, dtype: float64

In [1104]:
def average_product_dimensions(df):
        return df.groupby('product_category_name')[['product_length_cm', 'product_height_cm', 'product_width_cm']].mean().head(10)

average_product_dimensions(master_df)

,product_length_cm,product_height_cm,product_width_cm
product_category_name,,,
agro_industria_e_comercio,28.938679,23.787736,20.867925
alimentos,19.327451,13.666667,15.631373
alimentos_bebidas,21.751799,15.924460,16.676259
artes,49.043062,8.535885,36.531100
artes_e_artesanato,30.916667,10.916667,21.541667
artigos_de_festas,29.209302,15.883721,21.209302
artigos_de_natal,30.901961,17.431373,26.313725
audio,20.065934,9.478022,15.494505
automotivo,33.665171,16.102952,25.711688
bebes,35.163838,19.804504,28.548303

In [1105]:
def heaviest_product(df):
    return df.groupby('product_category_name')['product_weight_g'].max().sort_values(ascending=False).head(10)

heaviest_product(master_df)

product_category_name
cama_mesa_banho                      40425.0
automotivo                           30000.0
construcao_ferramentas_construcao    30000.0
consoles_games                       30000.0
casa_construcao                      30000.0
beleza_saude                         30000.0
brinquedos                           30000.0
bebes                                30000.0
agro_industria_e_comercio            30000.0
moveis_colchao_e_estofado            30000.0
Name: product_weight_g, dtype: float64

In [1106]:
def longest_description(df):
    return df.groupby('product_category_name')['product_description_lenght'].max().sort_values(ascending=False).head(10)

longest_description(master_df)

product_category_name
dvds_blu_ray              3992.0
automotivo                3988.0
esporte_lazer             3985.0
cool_stuff                3976.0
beleza_saude              3963.0
artes                     3954.0
consoles_games            3947.0
perfumaria                3947.0
informatica_acessorios    3940.0
alimentos                 3938.0
Name: product_description_lenght, dtype: float64

In [1107]:
def product_analysis(df):
    print('=' * 50)
    print('                Product Analysis ')
    print('=' * 50)

    print('\nProduct Performance')

    print(f'\nBest Selling Products: \n{best_selling_product(master_df)}')
    print(f'\nHighest Revenue Products: \n{highest_revenue_product(master_df)}')
    print(f'\nBest Selling category: \n{best_selling_categories(master_df)}')
    print(f'\nHighest Revenue Category: \n{highest_revenue_category(master_df)}')
    print(f'\nAverage Product price by Category: \n{average_product_price_by_category(master_df)}')

    print('\nProduct Characteristics')
    print(f'\nAverage weight by Category: \n{average_weight_by_category(master_df)}')
    print(f'\nAverage product dimensions by Category: \n{average_product_dimensions(master_df)}')
    print(f'\nHeaviest Products by Category: \n{heaviest_product(master_df)}')
    print(f'\nLongest product description by Category: \n{longest_description(master_df)}')

    print('=' * 50)

product_analysis(master_df)

==================================================
                Product Analysis
==================================================

Product Performance

Best Selling Products:
product_id
aca2eb7d00ea1a7b8ebd4e68314663af    527
99a4788cb24856965c36a24e339b6058    488
422879e10f46682990de24d770e7f83d    484
389d119b48cf3043d311335e499d9c6b    392
368c6c730842d78016ad823897a372db    388
53759a2ecddad2bb87a079a1f1519f73    373
d1c427060a0f73f6b889a5c7c61f2ac4    343
53b36df67ebb7c41585e8d54d6772e08    323
154e7e31ebfa092203795c972e5804a6    281
3dd2a17168ec895c781a9191c1e95ad7    274
Name: count, dtype: int64

Highest Revenue Products:
product_id
bb50f2e236e5eea0100680137654686c    63885.00
6cdd53843498f92890544667809f1595    54730.20
d6160fb7873f184099d9bc95e30376af    48899.34
d1c427060a0f73f6b889a5c7c61f2ac4    47214.51
99a4788cb24856965c36a24e339b6058    43025.56
3dd2a17168ec895c781a9191c1e95ad7    41082.60
25c38557cf793876c5abdd5931f922db    38907.32
5f504b3a1c75b73d6151be81eb05bdc9    37733.90
53b36df67ebb7c41585e8d54d6772e08    37683.42
aca2eb7d00ea1a7b8ebd4e68314663af    37608.90
Name: price, dtype: float64

Best Selling category:
product_category_name
cama_mesa_banho           11115
beleza_saude               9670
esporte_lazer              8641
moveis_decoracao           8334
informatica_acessorios     7827
utilidades_domesticas      6964
relogios_presentes         5991
telefonia                  4545
ferramentas_jardim         4347
automotivo                 4235
Name: order_id, dtype: int64

Highest Revenue Category:
product_category_name
beleza_saude              1258681.34
relogios_presentes        1205005.68
cama_mesa_banho           1036988.68
esporte_lazer              988048.97
informatica_acessorios     911954.32
moveis_decoracao           729762.49
cool_stuff                 635290.85
utilidades_domesticas      632248.66
automotivo                 592720.11
ferramentas_jardim         485256.46
Name: price, dtype: float64

Average Product price by Category:
product_category_name
pcs                                              1098.340542
portateis_casa_forno_e_cafe                       624.285658
eletrodomesticos_2                                476.124958
agro_industria_e_comercio                         342.124858
instrumentos_musicais                             281.616000
eletroportateis                                   280.778468
portateis_cozinha_e_preparadores_de_alimentos     264.568667
telefonia_fixa                                    225.693182
construcao_ferramentas_seguranca                  208.992371
relogios_presentes                                201.135984
Name: price, dtype: float64

Product Characteristics

Average weight by Category:
product_category_name
agro_industria_e_comercio    3625.113208
alimentos                     658.115686
alimentos_bebidas            1104.654676
artes                        1557.545455
artes_e_artesanato           1369.875000
artigos_de_festas            1997.674419
artigos_de_natal             1893.712418
audio                        1218.423077
automotivo                   2594.148288
bebes                        3273.405026
Name: product_weight_g, dtype: float64

Average product dimensions by Category:
                           product_length_cm  product_height_cm  \
product_category_name
agro_industria_e_comercio          28.938679          23.787736
alimentos                          19.327451          13.666667
alimentos_bebidas                  21.751799          15.924460
artes                              49.043062           8.535885
artes_e_artesanato                 30.916667          10.916667
artigos_de_festas                  29.209302          15.883721
artigos_de_natal                   30.901961          17.431373
audio                              20.065934           9.478022
automotivo                         33.665171          16.102952
bebes                              35.163838          19.804504

                           product_width_cm
product_category_name
agro_industria_e_comercio         20.867925
alimentos                         15.631373
alimentos_bebidas                 16.676259
artes                             36.531100
artes_e_artesanato                21.541667
artigos_de_festas                 21.209302
artigos_de_natal                  26.313725
audio                             15.494505
automotivo                        25.711688
bebes                             28.548303

Heaviest Products by Category:
product_category_name
cama_mesa_banho                      40425.0
automotivo                           30000.0
construcao_ferramentas_construcao    30000.0
consoles_games                       30000.0
casa_construcao                      30000.0
beleza_saude                         30000.0
brinquedos                           30000.0
bebes                                30000.0
agro_industria_e_comercio            30000.0
moveis_colchao_e_estofado            30000.0
Name: product_weight_g, dtype: float64

Longest product description by Category:
product_category_name
dvds_blu_ray              3992.0
automotivo                3988.0
esporte_lazer             3985.0
cool_stuff                3976.0
beleza_saude              3963.0
artes                     3954.0
consoles_games            3947.0
perfumaria                3947.0
informatica_acessorios    3940.0
alimentos                 3938.0
Name: product_description_lenght, dtype: float64
==================================================

# Customer Analysis

### Customer Overview

In [1108]:
master_df.head(1)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,...,price,freight_value,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-05-16 15:22:12,2017-05-23 10:47:57,...,124.99,21.88,moveis_escritorio,41.0,1141.0,1.0,8683.0,54.0,64.0,31.0

In [1109]:
temp_df = master_df.groupby('customer_unique_id')['order_id'].nunique().reset_index(name='order_count')

In [1110]:
def returning_customers(df):
    return df[df['order_count'] > 1].sort_values(by='order_count',ascending=False).count()

returning_customers(temp_df)

customer_unique_id    2913
order_count           2913
dtype: int64

In [1111]:
def one_time_customer(df):
    return df[df['order_count'] == 1].sort_values(by='order_count',ascending=False).count()

one_time_customer(temp_df)

customer_unique_id    92507
order_count           92507
dtype: int64

In [1112]:
def average_orders_per_customer(df):
    return df['order_count'].sum() / df['customer_unique_id'].count()  

average_orders_per_customer(temp_df)

np.float64(1.034018025571159)

### Customer Geography

In [1113]:
def customers_by_state(df):
    return df.groupby('customer_state')['customer_unique_id'].nunique().sort_values(ascending=False).head(10)

customers_by_state(master_df)

customer_state
SP    39981
RJ    12303
MG    11178
RS     5249
PR     4840
SC     3513
BA     3257
DF     2062
ES     1956
GO     1942
Name: customer_unique_id, dtype: int64

In [1114]:
def customers_by_city(df):
    return df.groupby('customer_city')['customer_unique_id'].nunique().sort_values(ascending=False).head(10)

customers_by_city(master_df)

customer_city
sao paulo                14865
rio de janeiro            6576
belo horizonte            2654
brasilia                  2056
curitiba                  1455
campinas                  1386
porto alegre              1320
salvador                  1202
guarulhos                 1143
sao bernardo do campo      898
Name: customer_unique_id, dtype: int64

### Customer spending

In [1115]:
def top_customer_by_spending(df):
    return df.assign(total = df['price'] + df['freight_value']).groupby('customer_unique_id')['total'].sum().sort_values(ascending=False).head(10)

top_customer_by_spending(master_df)

customer_unique_id
0a0a92112bd4c708ca5fde585afaa872    13664.08
da122df9eeddfedc1dc1f5349a1a690c     7571.63
763c8b1c9c68a0229c42c9fc6f662b93     7274.88
dc4802a71eae9be1dd28f5d788ceb526     6929.31
459bef486812aa25204be022145caa62     6922.21
ff4159b92c40ebe40454e3e6a7c35ed6     6726.66
4007669dec559734d6f53e029e360987     6081.54
5d0a2980b292d049061542014e8960bf     4809.44
eebb5dda148d3893cdaf5b5ca3040ccb     4764.34
48e1ac109decbb87765a3eade6854098     4681.78
Name: total, dtype: float64

In [1116]:
def average_customer_spending(df):
    return total_revenue(df).sum() / df['customer_unique_id'].nunique()

average_customer_spending(master_df)

np.float64(166.04017229092435)

In [1117]:
def top_customer_state_by_spending(df):
    return  df.assign(total = df['price'] + df['freight_value']).groupby('customer_state')['total'].mean().sort_values(ascending=False).head(10)

top_customer_state_by_spending(master_df)

customer_state
PB    234.199020
AL    216.732883
AC    213.801087
RO    207.043237
PA    201.525102
PI    199.506052
AP    198.326829
TO    194.775937
RR    193.550385
RN    192.618299
Name: total, dtype: float64

In [1118]:
def customer_analysis(df):
    print('=' * 50)
    print('                Customer Analysis ')
    print('=' * 50)

    print('\nCustomer Overview')

    print(f'\nReturning Customers: \n{returning_customers(temp_df)}')
    print(f'\nOne Time Customers: \n{one_time_customer(temp_df)}')
    print(f'\nAverage orders per Customer: \n{average_orders_per_customer(temp_df)}')

    print('\nCustomer Overview')

    print(f'\nCustomers by State: \n{customers_by_state(master_df)}')
    print(f'\nCustomer by City: \n{customers_by_city(master_df)}')

    print('\nCustomer Spending')
    print(f'\nTop Customes by Spending: \n{top_customer_by_spending(master_df)}')
    print(f'\nAverage Customer Spendin: \n{average_customer_spending(master_df)}')
    print(f'\nTop Customer States by Spending: \n{top_customer_state_by_spending(master_df)}')

    print('=' * 50)

customer_analysis(master_df)

==================================================
                Customer Analysis
==================================================

Customer Overview

Returning Customers:
customer_unique_id    2913
order_count           2913
dtype: int64

One Time Customers:
customer_unique_id    92507
order_count           92507
dtype: int64

Average orders per Customer:
1.034018025571159

Customer Overview

Customers by State:
customer_state
SP    39981
RJ    12303
MG    11178
RS     5249
PR     4840
SC     3513
BA     3257
DF     2062
ES     1956
GO     1942
Name: customer_unique_id, dtype: int64

Customer by City:
customer_city
sao paulo                14865
rio de janeiro            6576
belo horizonte            2654
brasilia                  2056
curitiba                  1455
campinas                  1386
porto alegre              1320
salvador                  1202
guarulhos                 1143
sao bernardo do campo      898
Name: customer_unique_id, dtype: int64

Customer Spending

Top Customes by Spending:
customer_unique_id
0a0a92112bd4c708ca5fde585afaa872    13664.08
da122df9eeddfedc1dc1f5349a1a690c     7571.63
763c8b1c9c68a0229c42c9fc6f662b93     7274.88
dc4802a71eae9be1dd28f5d788ceb526     6929.31
459bef486812aa25204be022145caa62     6922.21
ff4159b92c40ebe40454e3e6a7c35ed6     6726.66
4007669dec559734d6f53e029e360987     6081.54
5d0a2980b292d049061542014e8960bf     4809.44
eebb5dda148d3893cdaf5b5ca3040ccb     4764.34
48e1ac109decbb87765a3eade6854098     4681.78
Name: total, dtype: float64

Average Customer Spendin:
166.04017229092435

Top Customer States by Spending:
customer_state
PB    234.199020
AL    216.732883
AC    213.801087
RO    207.043237
PA    201.525102
PI    199.506052
AP    198.326829
TO    194.775937
RR    193.550385
RN    192.618299
Name: total, dtype: float64
==================================================